### ISSUE TITLE
Not able to Access Contacts in Android(though works, when page loads), It asks for Permission after page loads

### ISSUE THREAD

**Issue by priyansh360** [abhayastudios/nativescript-contacts-lite#10]
Hi Jonothan Solomon,
Hope you are good in this Covid-19
I am using this plugin in a ModalView , as i Click on the button to load the Modal , the permission is asked after the modal is loaded & then Permission error page comes as it ask for permission after the page loads . 

So basically it doesn't update permission on the runtime to the App, even after permission is granted by the User.
Please fix this issue.

Regards,
Priyansh Mishra

**Comment by abhayastudios** [comment]
Hi @priyansh360 I am not completely following what you mean. Can you please provide a test project that reproduces the issue?

**Comment by priyansh360** [comment]
Hi @Jonothan ,
I am sorry you didnt understand my concern as when i deny for Permission , how can i check for if after allowing the android Runtime permission for Contacts, the page is not refreshed as it is happening in iOS.
Currently i am not able to get the runtine success after allowing the contacts Permission

**Comment by abhayastudios** [comment]
@priyansh360 I'm sorry but I am still not sure I understand your question. Are you talking about the `demo-angular` project? If so please details step-by-step of what you are doing and what you expected to happen. Also if you are talking about your own project, please provide a test project that reproduces the issue and also step-by-step what you are doing and what you expected to happen.

I just ran the demo project on android, when I deny permissions of course I don't get any result, but the next time I run the app, it will again ask for permissions and if I then approve I will get all the contacts.

In the demo app, I am requesting to load the contacts only once in the [OnInit method](https://github.com/abhayastudios/nativescript-contacts-lite/blob/master/demo-angular/src/app/contacts/contacts.component.ts#L24-L26), but in a real app you would want to handle this differently, probably by catching the rejected promise and showing some alert to your user asking them to grant permissions and then try again.

**Comment by abhayastudios** [comment]
Closing due to no response

**Comment by priyansh360** [comment]
yes , sure i got the answer @abhayastudios  Thanks :)
