### ISSUE TITLE
Phone Number repeated with multiple account name, though in my contacts list, I don't have multiple account names

### ISSUE THREAD

**Issue by vasudevpareek07** [abhayastudios/nativescript-contacts-lite#11]
If I have 500 contacts, I get 1000 contacts (500 from my gmail account and 500 from my MI account), but in my contacts, while saving any contact, I haven't specified any account name. Any quick help will be appreciated. Thanks.

**Comment by abhayastudios** [comment]
I'm afraid I don't have a proper solution for this. Apparently your device (i am assuming it is a Xiaomi) stores the contacts twice (even without you asking for it) and this plugin correctly gets the contacts from all accounts.

If it makes sense in your app you could decide to look at one of the accounts, or filter out duplicates based on phone numbers  in your app.
