### ISSUE TITLE
Unexpected token: name (contacts)

### ISSUE THREAD

**Issue by andipahlevy** [abhayastudios/nativescript-contacts-lite#4]
Helo i get error

```
ERROR in app.android.js from UglifyJs
Unexpected token: name (contacts) [app.android.js:17451,4]
Preparing project...
Project successfully prepared (Android)
Successfully transferred app.css.
Successfully transferred app.js.
Refreshing application...
Successfully synced application org.nativescript.application on device efd668639 804.
ActivityManager: Start proc 15784:org.nativescript.application/u0a243 for activi ty org.nativescript.application/com.tns.NativeScriptActivity caller=null
JS: 'NativeScript-Vue has "Vue.config.silent" set to true, to see output logs se t it to false.'
JS: 'Loading contacts...'
JS: 'Woo Hoo, I have the power!'
JS: ==== object dump start ====
JS: ==== object dump end ====
```

**Script**
```
var Contacts = require("nativescript-contacts-lite");
var permissions = require( "nativescript-permissions" );
export default{

	mounted: function(){
		let desiredFields = ['display_name','phone'];
		let searchTerm = 'Jon';
		

		permissions.requestPermission(android.Manifest.permission.READ_CONTACTS, "I need these permissions because I'm cool")
		.then(function() {
			console.log("Woo Hoo, I have the power!");
		})
		.catch(function() {
			console.log("Uh oh, no permissions - plan B time!");
		});		
		console.log('Loading contacts...');
		let timer = new Date().getTime();
		 
		Contacts.getContacts(desiredFields,searchTerm).then((result) => {
			console.dir(result);
		}, (e) => { console.dir(e); });
	}

}
```

**package.json**
{
  "name": "belajar5",
  "version": "1.0.0",
  "description": "A native application built with NativeScript-Vue",
  "author": "levi",
  "license": "MIT",
  "scripts": {
    "build": "webpack --env.tnsAction build",
    "build:android": "npm run build -- --env.android",
    "build:ios": "npm run build -- --env.ios",
    "debug": "webpack --watch --env.tnsAction debug",
    "debug:android": "npm run debug -- --env.android",
    "debug:ios": "npm run debug -- --env.ios",
    "watch": "webpack --watch --env.tnsAction run",
    "watch:android": "npm run watch -- --env.android",
    "watch:ios": "npm run watch -- --env.ios",
    "clean": "rimraf dist"
  },
  "dependencies": {
    "nativescript-contacts-lite": "^0.2.5",
    "nativescript-permissions": "^1.2.3",
    "nativescript-theme-core": "^1.0.4",
    "nativescript-vue": "^1.3.1",
    "tns-core-modules": "~3.4.1",
    "vue-router": "^3.0.1",
    "vuex": "^3.0.1"
  },
  "devDependencies": {
    "babel-core": "^6.26.0",
    "babel-loader": "^7.1.4",
    "babel-plugin-transform-object-rest-spread": "^6.26.0",
    "babel-preset-env": "^1.7.0",
    "copy-webpack-plugin": "^4.5.1",
    "css-loader": "^0.28.11",
    "extract-text-webpack-plugin": "^3.0.2",
    "fs-extra": "^5.0.0",
    "nativescript-vue-externals": "^0.2.0",
    "nativescript-vue-loader": "^0.1.5",
    "nativescript-vue-target": "^0.1.0",
    "nativescript-vue-template-compiler": "^1.3.1",
    "nativescript-worker-loader": "^0.9.0",
    "node-sass": "^4.7.2",
    "ns-vue-loader": "^0.1.2",
    "optimize-css-assets-webpack-plugin": "^3.2.0",
    "rimraf": "^2.6.2",
    "sass-loader": "^6.0.7",
    "uglifyjs-webpack-plugin": "^1.2.5",
    "vue-template-compiler": "^2.5.16",
    "webpack": "^3.11.0",
    "webpack-synchronizable-shell-plugin": "0.0.7",
    "winston-color": "^1.0.0"
  }
}

**Comment by abhayastudios** [comment]
Hi @andipahlevy!

First of all, you don't need to handle the permissions because the plugin takes care of that. Even if you were to handle it then you should call `Contacts.getContacts` from within the `then()` callback. Now as you can see from the console, the contacts are being loaded before the permissions are granted (but again, no need because the plugin handles requesting permissions through the permissions plugin).

Anyway, from the first two lines of the console, I suspect there is a problem with the uglifier. Does it work if you run webpack without the uglify option? I will try to run webpack with uglify on the supplied demo project later when I have some time. I tested it with webpack and AoT, not sure if I tried with uglify. I would recommend you to run the demo project with webpack and uglify as well and let me know whether it works for you.

Cheers

**Comment by andipahlevy** [comment]
Yeps. Thank you for your feed back. the app is work fine.
Got it, i am gonna change my code.

Thanks @abhayastudios
