### ISSUE TITLE
Running getContacts or getContactsWorker on iOS make the app crash

### ISSUE THREAD

**Issue by sandoche** [abhayastudios/nativescript-contacts-lite#5]
Hi,

I developped an app on Android using nativescript-contacts-lite.
The problem is when I run the same code on iOS simulator it crashes. The simulator has contacts and is running on iOS 12. Note that there is not any pop up asking for permission before the crash. It just crashes!

I tried both getContactsWorker (that worked on Android) and getContacts, and no matter what are the fields. The problem is that there is no error in the NativeScript Console so I don't know how to debug it.

Any idea?

Best regards,

**Comment by abhayastudios** [comment]
Hi @sandoche!

Did you add the `NSContactsUsageDescription` key to your `Info.plist`? If not, then have a look at the [iOS specifics](https://github.com/abhayastudios/nativescript-contacts-lite#ios-specifics).

**Comment by sandoche** [comment]
I totally forgot, I was very stupid! Thanks a lot for your very quick answer! It works! Thanks a lot.
